### ISSUE TITLE
not adding trailing slash at end of the new-url/

### ISSUE THREAD

**Issue by yasirhaleem** [dhakerShiv/gatsby-plugin-client-side-redirect#11]
for me it output this `<script>window.location.href="/new-url"</script>` no trailing slash at end of url

but it in doc i see it as `<script>window.location.href="/new-url/"</script>`

**Comment by dhakerShiv** [comment]
@yasirhaleem Yes, no trailing slash one is correct, will update doc.

**Comment by yasirhaleem** [comment]
Thanks for your reply, can we have it as option ? i need trailing slash at the end
